Update head_tag.html
incubateur-territoires/discourse-incubateur pull request #3
Opened 2021-09-06 14:55 UTC by mariannehirsch-1

update subtitle

2021-09-06 14:56 UTC, mariannehirsch-1 commented
update subtitle in master

2021-09-06 14:58 UTC, mariannehirsch-1 reviewed
NC

2021-09-07 07:44 UTC, vinyll requested changes

2021-09-07 07:44 UTC, vinyll commented on common/head_tag.html
> +        <p>Des acteurs de l'Etat et d'autres collectivités pourrons vous répondre.</p>
pourront

2021-09-07 07:46 UTC, merged